"""Exports of a plan: PlantUML text and a Typst drawing.

The Typst drawing uses only Typst's built-in elements (`place`, `box`, `curve`,
`polygon`), so it compiles offline without packages. Boxes keep their canvas positions,
scaled to at most the text width; arrows go from box edge to box edge with a small
arrowhead computed here. All titles are escaped (see .claude/skills/typst-syntax).
"""

import math

from typst_writer.domain.planner import Plan, Step, auto_layout
from typst_writer.domain.typst_text import escape_markup

# Typst figure geometry (cm).
MAX_WIDTH = 16.0
BOX_WIDTH = 3.4
BOX_HEIGHT = 1.3
CM_PER_PIXEL = 0.0175  # 240 px between columns -> 4.2 cm
FONT_PT = 9.0
ARROW_LENGTH = 0.22
ARROW_HALF_WIDTH = 0.09
GAP = 0.04


def _plantuml_text(text: str) -> str:
    return text.replace('"', "'").replace("\\", "/")


def _alias(step_id: str) -> str:
    return "s_" + step_id.replace("-", "_")


def to_plantuml(plan: Plan, source: str) -> str:
    """A PlantUML diagram: one rectangle per step, an arrow from each dependency."""
    lines = [
        "@startuml",
        f"' Generated by the planner from {source}; changes here are overwritten.",
        f"title {_plantuml_text(plan.title)}",
        "skinparam rectangle {",
        "  RoundCorner 8",
        "}",
        "skinparam rectangle<<done>> {",
        "  BackgroundColor #E4E4E4",
        "  FontColor #555555",
        "}",
        "skinparam rectangle<<doing>> {",
        "  BorderThickness 2.5",
        "}",
    ]
    for step in plan.steps:
        lines.append(
            f'rectangle "{_plantuml_text(step.title)}" as {_alias(step.id)} <<{step.status}>>'
        )
    for step in plan.steps:
        for dependency in step.depends_on:
            lines.append(f"{_alias(dependency)} --> {_alias(step.id)}")
    lines += [
        "legend right",
        "  grey: done, thick border: in progress",
        "endlegend",
        "@enduml",
        "",
    ]
    return "\n".join(lines)


def _cm(value: float) -> str:
    return f"{value:.2f}cm"


def _edge(
    center: tuple[float, float], toward: tuple[float, float], w: float, h: float
) -> tuple[float, float]:
    """Where the line from `center` to `toward` leaves the box around `center`."""
    dx, dy = toward[0] - center[0], toward[1] - center[1]
    if dx == 0 and dy == 0:
        return center
    t = min(w / 2 / abs(dx) if dx else math.inf, h / 2 / abs(dy) if dy else math.inf)
    return center[0] + dx * t, center[1] + dy * t


def _arrow(start: tuple[float, float], end: tuple[float, float], scale: float) -> list[str]:
    """A line with an arrowhead at `end` (cm)."""
    length = math.dist(start, end)
    if length < ARROW_LENGTH * scale:
        return []
    ux, uy = (end[0] - start[0]) / length, (end[1] - start[1]) / length
    nx, ny = -uy, ux
    head, half = ARROW_LENGTH * scale, ARROW_HALF_WIDTH * scale
    base = (end[0] - ux * head, end[1] - uy * head)
    line_end = (end[0] - ux * head * 0.8, end[1] - uy * head * 0.8)
    left = (base[0] + nx * half, base[1] + ny * half)
    right = (base[0] - nx * half, base[1] - ny * half)

    def point(p: tuple[float, float]) -> str:
        return f"({_cm(p[0])}, {_cm(p[1])})"

    return [
        f"  #place(curve(stroke: 0.6pt, curve.move({point(start)}), "
        f"curve.line({point(line_end)})))",
        f"  #place(polygon(fill: black, {point(end)}, {point(left)}, {point(right)}))",
    ]


def _box(step: Step, left: float, top: float, scale: float) -> str:
    fill = "luma(228)" if step.status == "done" else "white"
    stroke = "1.4pt" if step.status == "doing" else "0.6pt"
    color = "luma(80)" if step.status == "done" else "black"
    title = escape_markup(step.title)
    return (
        f"  #place(dx: {_cm(left)}, dy: {_cm(top)}, box(width: {_cm(BOX_WIDTH * scale)}, "
        f"height: {_cm(BOX_HEIGHT * scale)}, inset: 3pt, radius: 3pt, fill: {fill}, "
        f"stroke: {stroke}, align(center + horizon, text(size: {FONT_PT * scale:.1f}pt, "
        f"fill: {color})[{title}])))"
    )


def to_typst(plan: Plan, source: str) -> str:
    """Typst code drawing the plan (content, to be `#include`d into a figure)."""
    header = f"// Generated by the planner from {source}; changes here are overwritten.\n"
    plan = auto_layout(plan)
    if not plan.steps:
        return header + "#block[_(This plan has no steps yet.)_]\n"
    xs = [s.x or 0.0 for s in plan.steps]
    ys = [s.y or 0.0 for s in plan.steps]
    span_x, span_y = max(xs) - min(xs), max(ys) - min(ys)
    # Shrink everything (boxes too) when the plan is wider than the text.
    natural = span_x * CM_PER_PIXEL + BOX_WIDTH
    scale = min(1.0, MAX_WIDTH / natural)
    per_pixel = CM_PER_PIXEL * scale
    w, h = BOX_WIDTH * scale, BOX_HEIGHT * scale
    corner = {
        s.id: ((x - min(xs)) * per_pixel, (y - min(ys)) * per_pixel)
        for s, x, y in zip(plan.steps, xs, ys, strict=True)
    }
    center = {k: (left + w / 2, top + h / 2) for k, (left, top) in corner.items()}
    lines = [
        header.rstrip("\n"),
        f"#block(width: {_cm(span_x * per_pixel + w)}, "
        f"height: {_cm(span_y * per_pixel + h)}, breakable: false)[",
    ]
    for step in plan.steps:
        for dependency in step.depends_on:
            start = _edge(center[dependency], center[step.id], w + 2 * GAP, h + 2 * GAP)
            end = _edge(center[step.id], center[dependency], w + 2 * GAP, h + 2 * GAP)
            lines += _arrow(start, end, scale)
    for step in plan.steps:
        left, top = corner[step.id]
        lines.append(_box(step, left, top, scale))
    lines.append("]")
    return "\n".join(lines) + "\n"


def include_line(name: str, title: str) -> str:
    """What to put into the document to show the exported plan as a figure."""
    return (
        f'#figure(include "/plans/{name}.typ", caption: [{escape_markup(title)}]) <fig:plan-{name}>'
    )
