"""Planner extension: plans as `plans/<name>.plan.json` in the open folder.

Every method refuses to work while the extension is turned off. Plan names are strict
slugs and every path is resolved by the workspace guard and must land directly in the
`plans` folder (a symlink leading elsewhere is refused). Saves carry the revision
(sha256 of the file) they were based on, so a change made elsewhere is never
overwritten. Generated exports (`.typ`, `.puml`) are regenerated on every save; a file
of that name that the planner did not generate is only replaced after confirmation.
"""

import hashlib
import re
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ValidationError

from typst_writer.domain.errors import (
    EntryExistsError,
    EntryNotFoundError,
    InvalidNameError,
    PlanConflictError,
    PlanInvalidError,
    PlannerDisabledError,
    TextTooLongError,
    WorkspaceError,
)
from typst_writer.domain.models import CompileResult
from typst_writer.domain.plan_export import include_line, to_plantuml, to_typst
from typst_writer.domain.planner import MAX_NOTES, Plan, Step, auto_layout, blocked, next_steps
from typst_writer.domain.typst_text import slugify
from typst_writer.services.compile import CompileService
from typst_writer.services.settings import SettingsService
from typst_writer.services.workspace import MAX_TEXT_BYTES, WorkspaceService

PLANS_FOLDER = "plans"
PLAN_SUFFIX = ".plan.json"
PLAN_NAME_PATTERN = r"^[a-z0-9][a-z0-9-]{0,59}$"
_PLAN_NAME = re.compile(PLAN_NAME_PATTERN)
GENERATED_MARKER = "Generated by the planner from "
NOTE_HELPER = ".typst-writer-note.typ"  # hidden: never mirrored from the workspace
NOTE_PREAMBLE = "#set page(width: 9cm, height: auto, margin: 6pt)\n#set text(size: 10pt)\n"

ExportKind = Literal["typst", "plantuml"]
_EXPORT_SUFFIX: dict[ExportKind, str] = {"typst": ".typ", "plantuml": ".puml"}


class PlanSummary(BaseModel):
    name: str
    path: str
    title: str
    steps: int
    done: int
    error: str | None = None  # the file is not a valid plan


class PlanDocument(BaseModel):
    name: str
    path: str
    plan: Plan  # steps without a position get one (auto layout)
    revision: str
    exports: list[ExportKind]


class WaitingStep(BaseModel):
    step: Step
    waits_for: list[str]


class NextView(BaseModel):
    next: list[Step]
    waiting: list[WaitingStep]


class ExportResult(BaseModel):
    path: str
    include: str | None = None  # the line that shows a Typst export as a figure


def plan_error(error: ValidationError) -> str:
    """The first validation problem as a sentence (`Step 2, title: …`)."""
    first = error.errors()[0]
    message = str(first["msg"]).removeprefix("Value error, ")
    location = [str(part) for part in first["loc"]]
    if len(location) >= 2 and location[0] == "steps" and location[1].isdigit():
        where = f"Step {int(location[1]) + 1}"
        rest = location[2:]
        return f"{where}, {' '.join(rest)}: {message}" if rest else f"{where}: {message}"
    return f"{' '.join(location)}: {message}" if location else message


def _revision(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _serialize(plan: Plan) -> str:
    return plan.model_dump_json(indent=2) + "\n"


class PlannerService:
    def __init__(
        self, workspace: WorkspaceService, settings: SettingsService, compile: CompileService
    ) -> None:
        self._workspace = workspace
        self._settings = settings
        self._compile = compile

    # --- paths ---------------------------------------------------------------------

    def _check_enabled(self) -> None:
        if not self._settings.ui().planner_enabled:
            raise PlannerDisabledError()

    def _folder(self, create: bool = False) -> Path | None:
        """The plans folder, or None if there is none yet (created on request)."""
        folder = self._workspace.guard.resolve(PLANS_FOLDER)
        if not folder.exists() and not folder.is_symlink():
            if not create:
                return None
            folder.mkdir()
        if not folder.is_dir():
            raise InvalidNameError(f"'{PLANS_FOLDER}' exists but is not a folder.")
        return folder

    def _path(self, filename: str, create_folder: bool = False) -> Path:
        """A file directly inside the plans folder (guard-resolved, links not followed out)."""
        folder = self._folder(create=create_folder)
        rel = f"{PLANS_FOLDER}/{filename}"
        if folder is None:
            raise EntryNotFoundError(rel)
        path = self._workspace.guard.resolve(rel)
        if path.parent != folder or path.name != filename:
            raise InvalidNameError(f"'{rel}' must be a file in the '{PLANS_FOLDER}' folder.")
        return path

    @staticmethod
    def _check_name(name: str) -> None:
        if not _PLAN_NAME.fullmatch(name):
            raise InvalidNameError(
                "Plan names use lower-case letters, digits and '-' (at most 60 characters)."
            )

    @staticmethod
    def _rel(name: str, suffix: str = PLAN_SUFFIX) -> str:
        return f"{PLANS_FOLDER}/{name}{suffix}"

    def _write(self, path: Path, content: str) -> None:
        data = content.encode("utf-8")
        if len(data) > MAX_TEXT_BYTES:
            raise TextTooLongError(f"Files larger than {MAX_TEXT_BYTES // 1_000_000} MB.")
        tmp = path.with_name(f".{path.name}.saving")
        tmp.write_bytes(data)
        tmp.replace(path)  # atomic: a crash never leaves a half-written file

    def _load(self, name: str) -> tuple[Plan, bytes]:
        self._check_name(name)
        path = self._path(name + PLAN_SUFFIX)
        if not path.is_file():
            raise EntryNotFoundError(self._rel(name))
        if path.stat().st_size > MAX_TEXT_BYTES:
            raise PlanInvalidError(f"'{self._rel(name)}' is too large.")
        data = path.read_bytes()
        try:
            return Plan.model_validate_json(data), data
        except ValidationError as e:
            reason = plan_error(e)
            raise PlanInvalidError(f"'{self._rel(name)}' is not a valid plan: {reason}") from e

    @staticmethod
    def _is_generated(path: Path) -> bool:
        try:
            with path.open(encoding="utf-8") as f:  # PlantUML: after @startuml
                return any(GENERATED_MARKER in f.readline() for _ in range(2))
        except (OSError, UnicodeDecodeError):
            return False

    def _exports(self, name: str) -> list[ExportKind]:
        kinds: list[ExportKind] = []
        for kind, suffix in _EXPORT_SUFFIX.items():
            path = self._path(name + suffix)
            if path.is_file() and self._is_generated(path):
                kinds.append(kind)
        return kinds

    def _render(self, plan: Plan, name: str, kind: ExportKind) -> str:
        source = self._rel(name)
        return to_typst(plan, source) if kind == "typst" else to_plantuml(plan, source)

    # --- plans ---------------------------------------------------------------------

    def list_plans(self) -> list[PlanSummary]:
        self._check_enabled()
        folder = self._folder()
        if folder is None:
            return []
        summaries: list[PlanSummary] = []
        for path in sorted(folder.iterdir(), key=lambda p: p.name.removesuffix(PLAN_SUFFIX)):
            name = path.name.removesuffix(PLAN_SUFFIX)
            if not path.name.endswith(PLAN_SUFFIX) or not _PLAN_NAME.fullmatch(name):
                continue
            try:
                plan, _ = self._load(name)
            except WorkspaceError as e:  # invalid, or a link leading elsewhere
                summaries.append(
                    PlanSummary(
                        name=name, path=self._rel(name), title=name, steps=0, done=0, error=str(e)
                    )
                )
                continue
            done = sum(1 for s in plan.steps if s.status == "done")
            summaries.append(
                PlanSummary(
                    name=name,
                    path=self._rel(name),
                    title=plan.title,
                    steps=len(plan.steps),
                    done=done,
                )
            )
        return summaries

    def read(self, name: str) -> PlanDocument:
        self._check_enabled()
        plan, data = self._load(name)
        return PlanDocument(
            name=name,
            path=self._rel(name),
            plan=auto_layout(plan),
            revision=_revision(data),
            exports=self._exports(name),
        )

    def create(self, title: str) -> PlanDocument:
        self._check_enabled()
        try:
            plan = Plan(title=title)
        except ValidationError as e:
            raise PlanInvalidError(plan_error(e)) from e
        self._folder(create=True)
        base = slugify(title, max_length=50) or "plan"
        name, n = base, 2
        while any(
            self._path(name + suffix).exists() or self._path(name + suffix).is_symlink()
            for suffix in (PLAN_SUFFIX, *_EXPORT_SUFFIX.values())
        ):
            name, n = f"{base}-{n}", n + 1
        self._write(self._path(name + PLAN_SUFFIX), _serialize(plan))
        return self.read(name)

    def save(self, name: str, raw: object, base_revision: str) -> PlanDocument:
        """Replace the plan, if the file is still the one the client read."""
        self._check_enabled()
        try:
            plan = Plan.model_validate(raw)
        except ValidationError as e:
            raise PlanInvalidError(plan_error(e)) from e
        _, data = self._load(name)
        if _revision(data) != base_revision:
            raise PlanConflictError()
        self._write(self._path(name + PLAN_SUFFIX), _serialize(plan))
        for kind in self._exports(name):  # keep included figures up to date
            self._write(self._path(name + _EXPORT_SUFFIX[kind]), self._render(plan, name, kind))
        return self.read(name)

    def delete(self, name: str) -> str:
        """Delete the plan file; exports stay (the document may still include them)."""
        self._check_enabled()
        self._check_name(name)
        path = self._path(name + PLAN_SUFFIX)
        if not path.is_file():
            raise EntryNotFoundError(self._rel(name))
        path.unlink()
        return self._rel(name)

    def export(self, name: str, kind: ExportKind, overwrite: bool = False) -> ExportResult:
        self._check_enabled()
        plan, _ = self._load(name)
        suffix = _EXPORT_SUFFIX[kind]
        path = self._path(name + suffix)
        if (path.exists() or path.is_symlink()) and not self._is_generated(path) and not overwrite:
            raise EntryExistsError(self._rel(name, suffix))
        if path.exists() and not path.is_file():
            raise EntryExistsError(self._rel(name, suffix))
        self._write(path, self._render(plan, name, kind))
        include = include_line(name, plan.title) if kind == "typst" else None
        return ExportResult(path=self._rel(name, suffix), include=include)

    def next(self, name: str) -> NextView:
        self._check_enabled()
        plan, _ = self._load(name)
        return NextView(
            next=next_steps(plan),
            waiting=[WaitingStep(step=s, waits_for=w) for s, w in blocked(plan)],
        )

    # --- notes ---------------------------------------------------------------------

    async def render_note(self, source: str) -> CompileResult:
        """Compile a step's notes on a narrow page, in the compile mirror (the open folder
        is never written). Problem lines refer to the notes."""
        self._check_enabled()
        if len(source) > MAX_NOTES:
            raise TextTooLongError(f"Notes are limited to {MAX_NOTES} characters.")
        root = self._workspace.guard.root
        result = await self._compile.render_helper(root, {}, NOTE_HELPER, NOTE_PREAMBLE + source)
        offset = NOTE_PREAMBLE.count("\n")
        problems = [
            p.model_copy(update={"file": "", "line": max(p.line - offset, 0)})
            if p.file == NOTE_HELPER
            else p
            for p in result.problems
        ]
        return result.model_copy(update={"problems": problems})
