"""Planner exports: PlantUML text and a Typst drawing that compiles."""

from pathlib import Path

import pytest
import typst

from typst_writer.domain.plan_export import include_line, to_plantuml, to_typst
from typst_writer.domain.planner import Plan

SAMPLE = Plan.model_validate(
    {
        "title": 'Arbeit "2026"',
        "steps": [
            {"id": "literatur", "title": "Literatur sichten", "status": "done", "x": 0, "y": 0},
            {
                "id": "gliederung",
                "title": "Gliederung",
                "status": "doing",
                "depends_on": ["literatur"],
                "x": 240,
                "y": 0,
            },
            {
                "id": "kapitel-1",
                "title": 'Kapitel "Einleitung"',
                "depends_on": ["gliederung"],
                "x": 480,
                "y": 110,
            },
        ],
    }
)


def test_plantuml_lists_steps_statuses_and_arrows() -> None:
    text = to_plantuml(SAMPLE, "plans/arbeit.plan.json")
    assert text.startswith("@startuml\n' Generated by the planner from plans/arbeit.plan.json")
    assert text.endswith("@enduml\n")
    assert "title Arbeit '2026'" in text
    assert 'rectangle "Literatur sichten" as s_literatur <<done>>' in text
    assert "rectangle \"Kapitel 'Einleitung'\" as s_kapitel_1 <<todo>>" in text
    assert "s_literatur --> s_gliederung" in text
    assert "s_gliederung --> s_kapitel_1" in text
    assert "skinparam rectangle<<doing>>" in text


def compile_project(tmp_path: Path, plan_code: str, main: str) -> None:
    (tmp_path / "plans").mkdir(exist_ok=True)
    (tmp_path / "plans" / "arbeit.typ").write_text(plan_code, encoding="utf-8")
    (tmp_path / "main.typ").write_text(main, encoding="utf-8")
    typst.compile(str(tmp_path / "main.typ"), root=str(tmp_path))  # raises on errors


def test_typst_drawing_compiles_inside_a_figure(tmp_path: Path) -> None:
    code = to_typst(SAMPLE, "plans/arbeit.plan.json")
    assert code.startswith("// Generated by the planner from plans/arbeit.plan.json")
    assert code.count("box(width:") == 3
    assert code.count("polygon(") == 2  # one arrowhead per dependency
    main = f"= Plan\n\n{include_line('arbeit', SAMPLE.title)}\n\nSiehe @fig:plan-arbeit.\n"
    compile_project(tmp_path, code, main)


@pytest.mark.parametrize(
    "title",
    [
        "#pagebreak()",
        "a ] b [ c",
        "$x$ und @ref",
        "// kein Kommentar",
        "*fett* _kursiv_ <label>",
        "= Überschrift",
        "1. Liste",
        "\\ ` ~",
    ],
)
def test_hostile_titles_are_shown_as_text(tmp_path: Path, title: str) -> None:
    plan = Plan.model_validate(
        {
            "title": title,
            "steps": [
                {"id": "a", "title": title},
                {"id": "b", "title": title, "depends_on": ["a"]},
            ],
        }
    )
    compile_project(
        tmp_path, to_typst(plan, "plans/x.plan.json"), include_line("arbeit", title) + "\n"
    )


def test_wide_plans_are_scaled_to_the_text_width(tmp_path: Path) -> None:
    steps = [{"id": f"s{i}", "title": f"Schritt {i}", "x": i * 240, "y": 0} for i in range(12)]
    plan = Plan.model_validate({"title": "Breit", "steps": steps})
    code = to_typst(plan, "plans/breit.plan.json")
    width = float(code.split("#block(width: ")[1].split("cm")[0])
    assert 15.5 < width <= 16.0
    compile_project(tmp_path, code, '#include "/plans/arbeit.typ"\n')


def test_plans_without_steps_or_positions(tmp_path: Path) -> None:
    empty = Plan.model_validate({"title": "Leer", "steps": []})
    compile_project(
        tmp_path, to_typst(empty, "plans/leer.plan.json"), '#include "/plans/arbeit.typ"\n'
    )
    unplaced = Plan.model_validate(
        {
            "title": "Neu",
            "steps": [{"id": "a", "title": "A"}, {"id": "b", "title": "B", "depends_on": ["a"]}],
        }
    )
    compile_project(
        tmp_path, to_typst(unplaced, "plans/neu.plan.json"), '#include "/plans/arbeit.typ"\n'
    )
    assert "polygon(" in to_typst(unplaced, "plans/neu.plan.json")
