// Dialogs for table, figure, equation and reference. The code is generated by the backend
// (POST /api/snippets/{id}/render) and shown live, so what you see is what gets inserted.

import { ApiError, api } from "../api/client";
import type { ReferenceTarget, Snippet, TargetKind, WorkspaceIndex } from "../api/types";
import { insertBlock, insertInline } from "../editor/snippetOps";
import { labelError, suggestLabel } from "../state/labels";
import { basename, el } from "../ui/dom";
import { showMessage } from "../ui/dialog";
import type { InsertContext } from "./insertToolbar";

type Params = Record<string, unknown>;

interface DialogSpec {
  title: string;
  snippet: Snippet;
  body: HTMLElement[];
  /** Current parameters, or an error message to show instead of rendering. */
  params(): Params | string;
  /** Block code goes on its own line; inline code replaces the selection. */
  block(): boolean;
  insertLabel?: string;
}

function field(label: string, input: HTMLElement, hint?: string): HTMLElement {
  const row = el("label", { class: "field" }, el("span", { class: "field-label" }, label), input);
  if (hint !== undefined) row.append(el("span", { class: "field-hint" }, hint));
  return row;
}

function textInput(value = "", attrs: Record<string, string> = {}): HTMLInputElement {
  const input = el("input", { type: "text", class: "text-input", spellcheck: "false", ...attrs });
  input.value = value;
  return input;
}

function numberInput(value: number, min: number, max: number): HTMLInputElement {
  const input = el("input", { type: "number", class: "text-input narrow", min: String(min), max: String(max), step: "1" });
  input.value = String(value);
  return input;
}

/** A label field that follows `source` (caption, image name) until the user edits it. */
function autoLabel(prefix: string, labels: ReadonlySet<string>): { input: HTMLInputElement; follow(text: string): void } {
  const input = textInput("", { placeholder: `${prefix}:name`, "aria-label": "Label" });
  let edited = false;
  input.addEventListener("input", () => (edited = input.value !== ""));
  return {
    input,
    follow(text: string): void {
      if (!edited) input.value = text.trim() === "" ? "" : suggestLabel(prefix, text, labels);
    },
  };
}

function openDialog(spec: DialogSpec, ctx: InsertContext): void {
  const dialog = el("dialog", { class: "dialog snippet-dialog" });
  const code = el("pre", { class: "code-preview", "aria-label": "Code that will be inserted" });
  const error = el("p", { class: "dialog-error", role: "alert" });
  const cancel = el("button", { type: "button", class: "button" }, "Cancel");
  const insert = el("button", { type: "submit", class: "button primary" }, spec.insertLabel ?? "Insert");
  const form = el("form", { class: "snippet-form" }, ...spec.body);

  let rendered: string | null = null;
  let generation = 0;
  let timer = 0;

  const refresh = async (): Promise<void> => {
    const mine = ++generation;
    const params = spec.params();
    if (typeof params === "string") {
      rendered = null;
      error.textContent = params;
      insert.disabled = true;
      return;
    }
    try {
      const result = await api.renderSnippet(spec.snippet.id, params, ctx.overlays());
      if (mine !== generation) return;
      rendered = result.code;
      code.textContent = result.code;
      error.textContent = "";
      insert.disabled = false;
    } catch (e: unknown) {
      if (mine !== generation) return;
      rendered = null;
      error.textContent = e instanceof Error ? e.message : String(e);
      insert.disabled = true;
    }
  };
  // Do not disable Insert while a refresh is pending: leaving a text field fires "change",
  // which would disable the button under the very click that caused it. submit() renders
  // fresh anyway.
  const schedule = (): void => {
    window.clearTimeout(timer);
    timer = window.setTimeout(() => void refresh(), 150);
  };
  form.addEventListener("input", schedule);
  form.addEventListener("change", schedule);

  const submit = async (): Promise<void> => {
    window.clearTimeout(timer);
    await refresh();
    const state = ctx.editor.activeState();
    if (rendered === null || state === null) return;
    // Close first: closing a <dialog> returns focus to the toolbar button that opened it,
    // and the user's next keystroke must go to the text instead.
    dialog.close();
    ctx.editor.apply(spec.block() ? insertBlock(state, rendered) : insertInline(state, rendered));
  };
  form.addEventListener("submit", (event) => {
    event.preventDefault();
    void submit();
  });
  insert.addEventListener("click", (event) => {
    event.preventDefault();
    void submit();
  });
  cancel.addEventListener("click", () => dialog.close());
  dialog.addEventListener("close", () => {
    window.clearTimeout(timer);
    dialog.remove();
    ctx.editor.focus();
  });

  dialog.append(
    el("h2", {}, spec.title),
    form,
    el("div", { class: "code-preview-wrap" }, el("span", { class: "field-label" }, "Inserted code"), code),
    error,
    el("div", { class: "dialog-buttons" }, cancel, insert),
  );
  document.body.append(dialog);
  dialog.showModal();
  (form.querySelector("input, textarea") as HTMLElement | null)?.focus();
  void refresh();
}

// --- table ---------------------------------------------------------------------------

function tableDialog(snippet: Snippet, ctx: InsertContext, index: WorkspaceIndex): DialogSpec {
  const labels = new Set(index.targets.filter((t) => t.kind !== "citation").map((t) => t.key));
  const rows = numberInput(3, 1, 200);
  const columns = numberInput(3, 1, 50);
  const header = el("input", { type: "checkbox", checked: "" });
  const caption = textInput("", { placeholder: "e.g. Messwerte der Versuchsreihe" });
  const label = autoLabel("tab", labels);
  caption.addEventListener("input", () => label.follow(caption.value));
  return {
    title: "Insert table",
    snippet,
    body: [
      el("div", { class: "field-row" }, field("Rows", rows), field("Columns", columns)),
      el("label", { class: "check" }, header, el("span", {}, "First row is a header")),
      field("Caption", caption),
      field("Label", label.input, "Refer to the table with this label. Leave empty for none."),
    ],
    params: () =>
      labelError(label.input.value.trim(), labels) ?? {
        rows: Number(rows.value),
        columns: Number(columns.value),
        header_row: header.checked,
        caption: caption.value,
        label: label.input.value.trim(),
        language: ctx.store.get().language,
      },
    block: () => true,
  };
}

// --- figure --------------------------------------------------------------------------

function figureDialog(snippet: Snippet, index: WorkspaceIndex): DialogSpec | string {
  if (index.images.length === 0) {
    return "There are no images in this folder yet. Copy PNG, JPG, SVG or PDF files into it, then try again.";
  }
  const labels = new Set(index.targets.filter((t) => t.kind !== "citation").map((t) => t.key));
  const filter = textInput("", { placeholder: "Filter images", "aria-label": "Filter images" });
  const list = el("div", { class: "pick-list", role: "listbox", "aria-label": "Images" });
  const caption = textInput("", { placeholder: "e.g. Aufbau des Experiments" });
  const width = el("input", { type: "range", min: "10", max: "100", step: "5", "aria-label": "Width" });
  width.value = "80";
  const widthOut = el("output", { class: "range-value" }, "80 %");
  width.addEventListener("input", () => (widthOut.textContent = `${width.value} %`));
  const label = autoLabel("fig", labels);
  let selected = index.images[0] ?? "";

  const renderList = (): void => {
    const needle = filter.value.toLowerCase();
    list.replaceChildren();
    for (const image of index.images.filter((i) => i.toLowerCase().includes(needle))) {
      const option = el(
        "button",
        { type: "button", class: "pick-row", role: "option", "aria-selected": String(image === selected), title: image },
        el("span", { class: "pick-main" }, basename(image)),
        el("span", { class: "pick-sub" }, image),
      );
      option.addEventListener("click", () => {
        selected = image;
        label.follow(caption.value || basename(image).replace(/\.[^.]+$/, ""));
        renderList();
        list.dispatchEvent(new Event("change", { bubbles: true }));
      });
      list.append(option);
    }
  };
  filter.addEventListener("input", renderList);
  caption.addEventListener("input", () => label.follow(caption.value || basename(selected).replace(/\.[^.]+$/, "")));
  renderList();
  label.follow(basename(selected).replace(/\.[^.]+$/, ""));

  return {
    title: "Insert figure",
    snippet,
    body: [
      filter,
      list,
      field("Caption", caption),
      field("Width", el("span", { class: "range-row" }, width, widthOut)),
      field("Label", label.input, "Refer to the figure with this label. Leave empty for none."),
    ],
    params: () =>
      labelError(label.input.value.trim(), labels) ?? {
        image: selected,
        caption: caption.value,
        width_percent: Number(width.value),
        label: label.input.value.trim(),
      },
    block: () => true,
  };
}

// --- equation ------------------------------------------------------------------------

function equationDialog(snippet: Snippet, index: WorkspaceIndex): DialogSpec {
  const labels = new Set(index.targets.filter((t) => t.kind !== "citation").map((t) => t.key));
  const math = el("textarea", { class: "text-input math-input", rows: "3", spellcheck: "false", placeholder: "a^2 + b^2 = c^2" });
  const inline = el("input", { type: "radio", name: "eq-display", value: "inline" });
  const block = el("input", { type: "radio", name: "eq-display", value: "block", checked: "" });
  const label = textInput("", { placeholder: "eq:name", "aria-label": "Label" });
  const labelRow = field("Label", label, "Give it a label to number it and refer to it.");
  const sync = (): void => {
    label.disabled = inline.checked;
    labelRow.classList.toggle("disabled", inline.checked);
  };
  inline.addEventListener("change", sync);
  block.addEventListener("change", sync);
  return {
    title: "Insert equation",
    snippet,
    body: [
      field("Formula (Typst math)", math, "Without $ signs, e.g. sum_(i=1)^n i or x^2 / 2"),
      el(
        "div",
        { class: "choice-row", role: "radiogroup", "aria-label": "Placement" },
        el("label", { class: "check" }, block, el("span", {}, "On its own line")),
        el("label", { class: "check" }, inline, el("span", {}, "Within the text")),
      ),
      labelRow,
    ],
    params: () => {
      if (math.value.trim() === "") return "Type a formula.";
      const labelValue = inline.checked ? "" : label.value.trim();
      return labelError(labelValue, labels) ?? { math: math.value, block: block.checked, label: labelValue };
    },
    block: () => block.checked,
  };
}

// --- reference -----------------------------------------------------------------------

const KIND_TITLES: [TargetKind, string][] = [
  ["heading", "Headings"],
  ["figure", "Figures"],
  ["table", "Tables"],
  ["equation", "Equations"],
  ["label", "Other labels"],
  ["citation", "Sources"],
];

function referenceDialog(snippet: Snippet, ctx: InsertContext, index: WorkspaceIndex): DialogSpec | string {
  if (index.targets.length === 0) {
    return "Nothing to refer to yet. Tables, figures and equations you insert with a label appear here, and so do the entries of a .bib file in the folder.";
  }
  const filter = textInput("", { placeholder: "Filter by label or text", "aria-label": "Filter" });
  const list = el("div", { class: "pick-list tall", role: "listbox", "aria-label": "Targets" });
  const seen = new Set<string>();
  // Unique keys, in the order the list shows them (headings, figures, … sources).
  const targets = KIND_TITLES.flatMap(([kind]) =>
    index.targets.filter((t) => t.kind === kind && !seen.has(t.key) && seen.add(t.key)),
  );
  let selected: ReferenceTarget | undefined = targets[0];

  const renderList = (): void => {
    const needle = filter.value.toLowerCase();
    list.replaceChildren();
    for (const [kind, title] of KIND_TITLES) {
      const members = targets.filter(
        (t) => t.kind === kind && (t.key + " " + t.description).toLowerCase().includes(needle),
      );
      if (members.length === 0) continue;
      list.append(el("div", { class: "pick-group", role: "presentation" }, title));
      for (const target of members) {
        const option = el(
          "button",
          { type: "button", class: "pick-row", role: "option", "aria-selected": String(target === selected), title: `${target.file}:${target.line}` },
          el("span", { class: "pick-main" }, target.description || target.key),
          el("span", { class: "pick-sub mono" }, target.key),
        );
        option.addEventListener("click", () => {
          selected = target;
          renderList();
          list.dispatchEvent(new Event("change", { bubbles: true }));
        });
        option.addEventListener("dblclick", () => option.closest("form")?.requestSubmit());
        list.append(option);
      }
    }
  };
  filter.addEventListener("input", renderList);
  renderList();

  const body: HTMLElement[] = [filter, list];
  const hasCitations = targets.some((t) => t.kind === "citation");
  const bibFile = index.bibliographies[0];
  if (hasCitations && !index.has_bibliography_call && bibFile !== undefined) {
    const add = el("button", { type: "button", class: "button" }, "Insert bibliography at the cursor");
    add.addEventListener("click", () => {
      void api.renderSnippet("bibliography", { file: bibFile }, ctx.overlays()).then(({ code }) => {
        add.closest("dialog")?.close();
        const state = ctx.editor.activeState();
        if (state !== null) ctx.editor.apply(insertBlock(state, code));
      });
    });
    body.push(
      el(
        "div",
        { class: "note" },
        el("p", {}, `Citations only work once the document prints a bibliography (from ${bibFile}).`),
        add,
      ),
    );
  }

  return {
    title: "Insert reference",
    snippet,
    body,
    params: () => (selected === undefined ? "Choose what to refer to." : { target: selected.key }),
    block: () => false,
  };
}

// --- entry point ---------------------------------------------------------------------

export async function openSnippetDialog(snippet: Snippet, ctx: InsertContext): Promise<void> {
  let index: WorkspaceIndex;
  try {
    index = await api.references(ctx.overlays());
  } catch (e: unknown) {
    await showMessage("Could not read the folder", e instanceof ApiError ? e.message : String(e));
    return;
  }
  let spec: DialogSpec | string;
  switch (snippet.dialog) {
    case "table":
      spec = tableDialog(snippet, ctx, index);
      break;
    case "figure":
      spec = figureDialog(snippet, index);
      break;
    case "equation":
      spec = equationDialog(snippet, index);
      break;
    case "reference":
      spec = referenceDialog(snippet, ctx, index);
      break;
    default:
      spec = `${snippet.label} is not available yet.`;
  }
  if (typeof spec === "string") {
    await showMessage(snippet.label, spec);
    return;
  }
  openDialog(spec, ctx);
}
