// Format controls at the start of the insert toolbar: font, size and line spacing. They
// show what is in effect at the cursor; picking a value formats the selection or, with
// nothing selected, sets the default of the whole document in the main file. The Typst
// code is generated by the backend (domain/formatting.py).

import { EditorSelection } from "@codemirror/state";

import { ApiError, api } from "../api/client";
import type { CurrentFormat, FormatChange, FormatOptions } from "../api/types";
import type { EditorPane } from "../editor/editor";
import type { AppState, Store } from "../state/store";
import { showMessage } from "../ui/dialog";
import { basename, el } from "../ui/dom";

export interface FormatContext {
  store: Store<AppState>;
  editor: EditorPane;
  openDoc(path: string): Promise<void>;
  notify(text: string): void;
}

type Kind = FormatChange["kind"];
const CURRENT_DELAY_MS = 300;
const MAIN_CACHE_MS = 10_000;

// --- pure helpers (tested) --------------------------------------------------------------

/** "14pt" -> "14"; other units are shown as written. */
export function sizeLabel(size: string | null, fallback: number): string {
  if (size === null) return String(fallback);
  const pt = /^(\d+(?:\.\d+)?)pt$/.exec(size.trim());
  return pt?.[1] ?? size;
}

/** The option label for a leading ("1.05em" -> "1.5"), or the raw value. */
export function spacingLabel(leading: string | null, options: FormatOptions["line_spacing"]): string {
  const match = options.find((o) => (leading === null ? o.default : o.leading === leading.trim()));
  return match?.label ?? leading ?? "";
}

/** Fonts whose name contains every typed word (case-insensitive), built-in ones first. */
export function filterFonts(fonts: FormatOptions["fonts"], query: string): FormatOptions["fonts"] {
  const words = query.toLowerCase().split(/\s+/).filter(Boolean);
  return fonts.filter((f) => words.every((w) => f.family.toLowerCase().includes(w)));
}

/** What a change applies to, for tooltips and the popup header. */
export function targetText(kind: Kind, selectionEmpty: boolean, main: string | null): string {
  if (selectionEmpty) return main === null ? "Whole document (set a main file first)" : `Whole document (${basename(main)})`;
  return kind === "line_spacing" ? "The selected paragraphs" : "Selected text";
}

// --- popup ------------------------------------------------------------------------------

let openPopup: HTMLElement | null = null;

function closePopup(): void {
  openPopup?.remove();
  openPopup = null;
}

let listening = false;

/** Clicking anywhere else closes the popup (registered on first use, not at import). */
function closeOnOutsideClick(): void {
  if (listening) return;
  listening = true;
  document.addEventListener("mousedown", (event) => {
    if (openPopup && !openPopup.contains(event.target as Node)) closePopup();
  });
}

interface Choice {
  value: string;
  label: string;
  hint?: string;
  fontFamily?: string;
  section?: string;
}

function showPopup(
  anchor: HTMLElement,
  heading: string,
  choices: Choice[],
  selected: string,
  pick: (value: string) => void,
  options: { filter?: string; custom?: { label: string; pattern: RegExp } } = {},
): void {
  closePopup();
  closeOnOutsideClick();
  const list = el("div", { class: "format-list", role: "listbox", "aria-label": heading });
  const popup = el("div", { class: "format-popup", role: "dialog", "aria-label": heading }, el("p", { class: "format-target" }, heading));
  const choose = (value: string): void => {
    closePopup();
    pick(value);
  };
  const render = (query: string): void => {
    list.replaceChildren();
    let section = "";
    const shown = options.filter === undefined ? choices : choices.filter((c) => filterFonts([{ family: c.label, builtin: false }], query).length > 0);
    for (const choice of shown) {
      if (choice.section !== undefined && choice.section !== section) {
        section = choice.section;
        list.append(el("p", { class: "format-section" }, section));
      }
      const option = el(
        "button",
        { type: "button", role: "option", class: "format-option", "aria-selected": String(choice.value === selected), "data-value": choice.value },
        el("span", { class: "format-option-label" }, choice.label),
      );
      if (choice.hint) option.append(el("span", { class: "format-option-hint" }, choice.hint));
      if (choice.fontFamily !== undefined) {
        (option.firstChild as HTMLElement).style.fontFamily = `${JSON.stringify(choice.fontFamily)}, var(--font-ui)`;
      }
      option.addEventListener("click", () => choose(choice.value));
      list.append(option);
    }
    if (shown.length === 0) list.append(el("p", { class: "format-empty" }, "No font matches."));
  };
  let input: HTMLInputElement | null = null;
  if (options.filter !== undefined || options.custom !== undefined) {
    const custom = options.custom;
    input = el("input", {
      class: "format-input",
      type: "text",
      placeholder: options.filter ?? custom?.label ?? "",
      "aria-label": options.filter ?? custom?.label ?? "",
      spellcheck: "false",
    });
    const field = input;
    field.addEventListener("input", () => {
      if (options.filter !== undefined) render(field.value);
    });
    field.addEventListener("keydown", (event) => {
      if (event.key === "Enter") {
        event.preventDefault();
        const typed = field.value.trim().toLowerCase();
        const shown = [...list.querySelectorAll<HTMLButtonElement>(".format-option")];
        const exact = shown.find((o) => o.dataset["value"]?.toLowerCase() === typed);
        if (custom !== undefined && custom.pattern.test(field.value.trim())) choose(field.value.trim().replace(",", "."));
        else if (options.filter !== undefined) (exact ?? shown[0])?.click();
      } else if (event.key === "ArrowDown") {
        event.preventDefault();
        list.querySelector<HTMLButtonElement>(".format-option")?.focus();
      }
    });
    popup.append(input);
  }
  popup.append(list);
  popup.addEventListener("keydown", (event) => {
    const buttons = [...list.querySelectorAll<HTMLButtonElement>(".format-option")];
    const index = buttons.indexOf(document.activeElement as HTMLButtonElement);
    if (event.key === "Escape") {
      event.preventDefault();
      closePopup();
      anchor.focus();
    } else if (event.key === "ArrowDown" && index >= 0) {
      event.preventDefault();
      buttons[Math.min(index + 1, buttons.length - 1)]?.focus();
    } else if (event.key === "ArrowUp" && index >= 0) {
      event.preventDefault();
      if (index === 0 && input) input.focus();
      else buttons[index - 1]?.focus();
    }
  });
  render("");
  const rect = anchor.getBoundingClientRect();
  popup.style.left = `${Math.round(rect.left)}px`;
  popup.style.top = `${Math.round(rect.bottom + 4)}px`;
  document.body.append(popup);
  openPopup = popup;
  (input ?? list.querySelector<HTMLButtonElement>('[aria-selected="true"]') ?? list.querySelector<HTMLButtonElement>(".format-option"))?.focus();
  list.querySelector('[aria-selected="true"]')?.scrollIntoView({ block: "nearest" });
}

// --- controls ---------------------------------------------------------------------------

function control(className: string, title: string, ...children: (Node | string)[]): HTMLButtonElement {
  return el(
    "button",
    { type: "button", class: `tool format-control ${className}`, title, "aria-haspopup": "dialog" },
    ...children,
    el("span", { class: "caret", "aria-hidden": "true" }),
  );
}

export async function mountFormatControls(host: HTMLElement, ctx: FormatContext): Promise<void> {
  const options = await api.formatOptions();
  const fontName = el("span", { class: "format-value format-font-name" }, options.default_font);
  const sizeValue = el("span", { class: "format-value" }, String(options.default_size));
  const spacingValue = el("span", { class: "format-value" }, spacingLabel(null, options.line_spacing));
  const font = control("format-font", "Font", fontName);
  const size = control("format-size", "Font size (pt)", sizeValue);
  const spacing = control(
    "format-spacing",
    "Line spacing",
    el("span", { class: "format-spacing-icon", "aria-hidden": "true" }, el("span"), el("span"), el("span")),
    spacingValue,
  );
  host.append(el("div", { class: "format-group", role: "group", "aria-label": "Format" }, font, size, spacing));

  let current: CurrentFormat = { font: null, size: null, leading: null };
  const mainCache = new Map<string, { content: string; at: number }>();

  const mainPath = (): string | null => ctx.store.get().workspace?.main ?? null;
  const mainContent = async (path: string): Promise<string> => {
    const open = ctx.editor.content(path);
    if (open !== null) return open;
    const cached = mainCache.get(path);
    if (cached && Date.now() - cached.at < MAIN_CACHE_MS) return cached.content;
    const content = (await api.readFile(path)).content;
    mainCache.set(path, { content, at: Date.now() });
    return content;
  };
  const selectionEmpty = (): boolean => ctx.editor.activeState()?.selection.main.empty ?? true;

  const show = (): void => {
    fontName.textContent = current.font ?? options.default_font;
    fontName.style.fontFamily = `${JSON.stringify(current.font ?? options.default_font)}, var(--font-ui)`;
    sizeValue.textContent = sizeLabel(current.size, options.default_size);
    spacingValue.textContent = spacingLabel(current.leading, options.line_spacing);
    const empty = selectionEmpty();
    font.title = `Font: ${targetText("font", empty, mainPath())}`;
    size.title = `Font size: ${targetText("size", empty, mainPath())}`;
    spacing.title = `Line spacing: ${targetText("line_spacing", empty, mainPath())}`;
  };

  let timer = 0;
  let request = 0;
  const refresh = (): void => {
    window.clearTimeout(timer);
    timer = window.setTimeout(() => {
      const state = ctx.editor.activeState();
      const active = ctx.store.get().active;
      const main = mainPath();
      if (state === null || active === null || !active.endsWith(".typ")) return;
      const mine = ++request;
      void (async () => {
        try {
          const other = main !== null && main !== active ? await mainContent(main) : null;
          const { from, to, head, empty } = state.selection.main;
          const found = await api.currentFormat(state.doc.toString(), empty ? head : from, other, empty ? null : to);
          if (mine === request) {
            current = found;
            show();
          }
        } catch {
          // Keep the last values; this is only a display.
        }
      })();
    }, CURRENT_DELAY_MS);
  };

  const run = async (change: FormatChange): Promise<void> => {
    const state = ctx.editor.activeState();
    const active = ctx.store.get().active;
    if (state === null || active === null) return;
    const selection = state.selection.main;
    try {
      if (!selection.empty) {
        const edit = await api.formatSelection(state.doc.toString(), selection.from, selection.to, change);
        const now = ctx.editor.activeState();
        if (now === null || now.doc.toString() !== state.doc.toString()) return; // edited meanwhile
        const changes = now.changes({ from: edit.start, to: edit.end, insert: edit.insert });
        const from = Math.min(changes.mapPos(selection.from, -1), edit.start);
        const to = Math.max(changes.mapPos(selection.to, 1), edit.start + edit.insert.length);
        ctx.editor.apply({ changes, selection: EditorSelection.range(from, to), userEvent: "input.format" });
      } else {
        const main = mainPath();
        if (main === null) {
          await showMessage("No main file", "Right-click a .typ file and choose Set as main file, then set the document's font, size or spacing.");
          return;
        }
        const edit = await api.formatDocument(await mainContent(main), change);
        await ctx.openDoc(main);
        ctx.editor.apply({ changes: { from: edit.start, to: edit.end, insert: edit.insert }, userEvent: "input.format" });
        mainCache.delete(main);
        ctx.notify(`Set for the whole document in ${basename(main)}`);
      }
      refresh();
    } catch (error) {
      const text = error instanceof ApiError ? error.message : String(error);
      await showMessage("Cannot format this", text);
    }
  };

  font.addEventListener("click", () => {
    const choices: Choice[] = options.fonts.map((f) => ({
      value: f.family,
      label: f.family,
      fontFamily: f.family,
      section: f.builtin ? "Works on every computer" : "Installed on this computer",
    }));
    showPopup(font, targetText("font", selectionEmpty(), mainPath()), choices, current.font ?? options.default_font, (value) => void run({ kind: "font", value }), {
      filter: "Search fonts",
    });
  });
  size.addEventListener("click", () => {
    const choices: Choice[] = options.sizes.map((s) => ({
      value: String(s),
      label: String(s),
      ...(s === options.default_size ? { hint: "default" } : {}),
    }));
    showPopup(size, targetText("size", selectionEmpty(), mainPath()), choices, sizeLabel(current.size, options.default_size), (value) => void run({ kind: "size", value }), {
      custom: { label: "Other size (pt)", pattern: /^\d{1,2}([.,]\d)?$/ },
    });
  });
  spacing.addEventListener("click", () => {
    const choices: Choice[] = options.line_spacing.map((o) => ({
      value: o.label,
      label: o.label,
      ...(o.default ? { hint: "default" } : {}),
    }));
    showPopup(spacing, targetText("line_spacing", selectionEmpty(), mainPath()), choices, spacingLabel(current.leading, options.line_spacing), (value) =>
      void run({ kind: "line_spacing", value }),
    );
  });

  ctx.store.subscribe((state, previous) => {
    const disabled = state.active === null || !state.active.endsWith(".typ");
    for (const button of [font, size, spacing]) button.disabled = disabled;
    if (state.cursor !== previous.cursor || state.active !== previous.active || state.docs !== previous.docs) refresh();
    if (state.workspace !== previous.workspace) mainCache.clear();
  });
  show();
}
